"""added MESSAGE_VISIBLE_TO

Revision ID: caf96a04a1d4
Revises: f0fc6a76f3aa
Create Date: 2021-06-06 13:23:20.662323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf96a04a1d4'
down_revision = 'f0fc6a76f3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('MESSAGE_VISIBLE_TO', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'MESSAGE_VISIBLE_TO')
    # ### end Alembic commands ###
